# ═══════════════════════════════════════════════════════════
# summary.py -- L2 SummaryMemory (Mid-term, 30-day rolling)
#
# WHAT THIS MODULE DOES:
#   Creates a compressed summary of the past 30 days.
#   Think of it as a "monthly report" -- the AI reads through
#   your recent conversations and permanent memories, then
#   writes a condensed version.
#
# WHY SUMMARIZE?
#   Loading 30 days of raw conversations into an LLM prompt
#   would use too many tokens. A summary gives the AI the
#   "big picture" without the cost.
#
# HOW IT CONNECTS:
#   L1 (session.py)  = raw conversations (3 days)
#   L2 (THIS FILE)   = compressed summary (30 days)
#   L3 (permanent.py) = individual important memories (forever)
#
# HOW TO CUSTOMIZE:
#   The summary is generated by YOUR AI callback.
#   You control what model is used and how the summary is formatted.
#
# DEPENDS ON:
#   session.py (L1 -- reads recent logs)
#   permanent.py (L3 -- reads important memories)
#   utils.py (now_iso)
# ═══════════════════════════════════════════════════════════

from __future__ import annotations

import logging
from collections.abc import Callable
from typing import Any

from sandclaw_memory.utils import now_iso

__all__ = ["SummaryMemory"]

logger = logging.getLogger(__name__)


class SummaryMemory:
    """L2 mid-term memory -- 30-day rolling summary.

    This layer collects data from L1 (sessions) and L3 (archive),
    then uses an AI callback to generate a compressed summary.

    Usage:
        summary_mem = SummaryMemory()
        raw_data = summary_mem.collect_data(session, archive, days=30)
        summary_text = summary_mem.generate(raw_data, llm_callback=my_summarizer)
    """

    def __init__(self, summary_days: int = 30) -> None:
        """Initialize SummaryMemory.

        Args:
            summary_days: How many days of data to summarize (default 30).

        HOW TO CUSTOMIZE:
            # Summarize only the last 7 days:
            summary = SummaryMemory(summary_days=7)
        """
        self.summary_days = summary_days
        self._cached_summary: str = ""
        self._cached_at: str = ""

    def collect_data(
        self,
        session: Any,
        archive: Any,
        days: int | None = None,
    ) -> dict[str, Any]:
        """Collect raw data from L1 and L3 for summarization.

        Args:
            session: A SessionMemory instance (L1).
            archive: An ArchiveMemory instance (L3).
            days: Override for summary_days.

        Returns:
            Dict with "session_context", "archive_entries", and "collected_at".

        HOW IT WORKS:
            1. Grabs recent conversation context from L1
            2. Grabs recent permanent memories from L3
            3. Returns both in a dict for the AI to summarize
        """
        target_days = days or self.summary_days

        # ─── L1: Recent session context ───
        session_context = ""
        if session is not None:
            session_context = session.get_context()

        # ─── L3: Recent archive entries ───
        archive_entries: list[dict[str, Any]] = []
        if archive is not None:
            from datetime import datetime, timedelta, timezone

            end = datetime.now(timezone.utc).isoformat()
            start = (datetime.now(timezone.utc) - timedelta(days=target_days)).isoformat()
            entries = archive.search_by_date(start, end, limit=100)
            archive_entries = [
                {"content": e.content, "tags": e.tags, "created_at": e.created_at}
                for e in entries
            ]

        return {
            "session_context": session_context,
            "archive_entries": archive_entries,
            "collected_at": now_iso(),
            "days": target_days,
        }

    def generate(
        self,
        collected_data: dict[str, Any],
        llm_callback: Callable[[str], str] | None = None,
    ) -> str:
        """Generate a summary from collected data using an AI callback.

        Args:
            collected_data: Output from collect_data().
            llm_callback: A function that takes a prompt string and
                returns a summary string. If None, returns raw data
                as a simple concatenation.

        Returns:
            The generated summary text.

        HOW IT WORKS:
            1. Builds a prompt from the collected data
            2. Calls your AI callback with the prompt
            3. Caches the result for get_summary()

        HOW TO CUSTOMIZE:
            # Use any AI model you want:
            def my_summarizer(prompt):
                resp = openai.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{"role": "user", "content": prompt}]
                )
                return resp.choices[0].message.content

            summary = summary_mem.generate(data, llm_callback=my_summarizer)
        """
        # ─── Build prompt ───
        parts: list[str] = []
        parts.append("Summarize the following memory data into a concise report.")
        parts.append(f"Time period: last {collected_data.get('days', 30)} days.\n")

        session_ctx = collected_data.get("session_context", "")
        if session_ctx:
            parts.append("## Recent Conversations")
            # Limit to avoid excessive tokens
            parts.append(session_ctx[:5000])

        entries = collected_data.get("archive_entries", [])
        if entries:
            parts.append("\n## Important Memories")
            for entry in entries[:30]:
                tags = ", ".join(entry.get("tags", []))
                parts.append(f"- [{tags}] {entry['content'][:200]}")

        prompt = "\n".join(parts)

        # ─── Generate summary ───
        if llm_callback is not None:
            try:
                summary = llm_callback(prompt)
            except Exception as e:
                logger.warning("Summary generation failed: %s", e)
                summary = self._fallback_summary(collected_data)
        else:
            summary = self._fallback_summary(collected_data)

        # ─── Cache ───
        self._cached_summary = summary
        self._cached_at = now_iso()

        logger.info(
            "Generated %d-day summary (%d chars)",
            collected_data.get("days", 30),
            len(summary),
        )
        return summary

    def get_summary(self) -> str:
        """Get the most recently generated summary.

        Returns:
            The cached summary text, or empty string if none generated yet.
        """
        return self._cached_summary

    @staticmethod
    def _fallback_summary(data: dict[str, Any]) -> str:
        """Simple fallback when no LLM callback is provided.

        Just concatenates the data -- not a real summary, but
        better than returning nothing.
        """
        parts = [f"## {data.get('days', 30)}-Day Summary (auto-generated)\n"]

        entries = data.get("archive_entries", [])
        if entries:
            parts.append(f"Total memories: {len(entries)}")
            for entry in entries[:10]:
                parts.append(f"- {entry['content'][:100]}")

        return "\n".join(parts)
